# Generated by Django 5.1.4 on 2025-01-07 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                (
                    "company_logo",
                    models.ImageField(
                        default="company_images/company_logos/blank-pic.png",
                        upload_to="company_images",
                    ),
                ),
                (
                    "company_pictures",
                    models.ImageField(
                        default="company_images/blank-pic.png",
                        upload_to="company_images",
                    ),
                ),
                ("company_description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("contact_website", models.URLField(blank=True, null=True)),
                ("company_created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="following_employer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_on", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="employers.employerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("job_location", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("", "Select Location type"),
                            ("On-Site", "On-Site"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("", "Select job type"),
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Contract", "Contract"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("", "Select Experience Level"),
                            ("Entry", "Entry Level"),
                            ("Mid", "Mid Level"),
                            ("Senior", "Senior Level"),
                        ],
                        max_length=50,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, editable=False, unique=True)),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="employers.employerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-posted_on"],
            },
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_employer",
                        to="employers.employerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("employer", "user")},
            },
        ),
    ]
