# Generated by Django 5.1.4 on 2025-01-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "ordering": ["-posted_on"],
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
        migrations.AddField(
            model_name="jobposting",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("Entry", "Entry Level"),
                    ("Mid", "Mid Level"),
                    ("Senior", "Senior Level"),
                ],
                default="Entry",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("On-Site", "On-Site"),
                    ("Remote", "Remote"),
                    ("Hybrid", "Hybrid"),
                ],
                default="On-Site",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
