# Generated by Django 5.1.4 on 2025-01-06 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0003_alter_jobposting_experience_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_employer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_employer",
                to="employers.employerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("employer", "user")},
        ),
    ]
